name = str(input("Enter your name: "))
surname = str(input("Enter your surname: "))
age = int(input("Enter your age: "))
address = (input("Enter your living address: "))
gmail = (input("Enter your Gmail: "))
print(name,surname,"age",age, address, gmail)